Create twitter_bot.py
it run but respond this errors
Traceback (most recent call last):
  File "/Users/mahdi/Downloads/twiter_bot.py", line 33, in <module>
    auth = tweepy.AppAuthHandler(CLIENT_ID,CLIENT_SECRET)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweepy/auth.py", line 169, in __init__
    super().__init__(consumer_key, consumer_secret)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tweepy/auth.py", line 148, in __init__
    raise TweepyException('Expected token_type to equal "bearer", '
tweepy.errors.TweepyException: Expected token_type to equal "bearer", but got None instead